# Generated by Django 5.0.6 on 2024-06-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_author_customuser_favorite_authors_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_authors',
            field=models.ManyToManyField(null=True, to='account.author'),
        ),
    ]
